sudo: required
services:
  - docker

before_install: -docker build -t axelongaro/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true axelongaro/react-test npm test

after_success:
  - docker build -t axelongaro/multi-client ./client
  - docker build -t axelongaro/multi-nginx ./nginx
  - docker build -t axelongaro/multi-server ./server
  - docker build -t axelongaro/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push axelongaro/multi-client
  - docker push axelongaro/multi-nginx
  - docker push axelongaro/multi-server
  - docker push axelongaro/multi-worker
